import { Flame, Phone, Radio } from 'lucide-react';
import { Link, NavLink } from 'react-router-dom';
import { neoButton } from '../../utils/theme';

const links = [{ to: '/', label: 'Home' }, { to: '/dashboard', label: 'Dashboard' }, { to: '/advisory', label: 'Advisory' }, { to: '/emergency', label: 'Emergency' }, { to: '/reports', label: 'Reports' }, { to: '/about', label: 'About' }];

export default function Navbar() {
  return <header className="sticky top-0 z-50 border-b border-slate-200 bg-[#FAFAFA]/95 px-4 py-3 backdrop-blur"><div className="mx-auto max-w-7xl overflow-hidden rounded-lg bg-slate-900 py-1.5 text-center text-xs font-medium text-slate-100"><span className="inline-flex items-center gap-2"><Radio size={13} className="animate-pulse text-emerald-400" />LIVE TELEMETRY: Nagpur AWS station reporting 46.2°C · Forecast confidence 96% · 124 nodes online</span></div><nav className="mx-auto mt-3 flex max-w-7xl items-center gap-3 overflow-x-auto rounded-2xl border-2 border-slate-900 bg-white px-4 py-3 shadow-[3px_3px_0px_0px_#0f172a]" aria-label="Main navigation"><Link to="/" className="flex shrink-0 items-center gap-2 text-lg font-black tracking-tight text-slate-900"><span className="rounded-lg border border-slate-900 bg-amber-100 p-1.5 text-red-700"><Flame size={20} /></span>suryakavach.ai</Link><div className="flex shrink-0 items-center gap-1 border-l border-slate-200 pl-3 text-sm font-medium">{links.map((link) => <NavLink key={link.to} to={link.to} className={({ isActive }) => `rounded-lg px-3 py-2 transition-colors ${isActive ? 'bg-slate-900 text-white' : 'text-slate-600 hover:bg-slate-100'}`}>{link.label}</NavLink>)}</div><a href="tel:108" className={`${neoButton} ml-auto flex shrink-0 items-center gap-2 bg-red-600 text-white`}><Phone size={16} />108 Heat Line</a></nav></header>;
}
