import { Flame, Menu, Phone, Radio, X } from 'lucide-react';
import { useState } from 'react';
import { Link, NavLink } from 'react-router-dom';
import { neoButton } from '../../utils/theme';

const links = [{ to: '/', label: 'Home' }, { to: '/dashboard', label: 'Dashboard' }, { to: '/advisory', label: 'Advisory' }, { to: '/emergency', label: 'Emergency' }, { to: '/reports', label: 'Reports' }, { to: '/about', label: 'About' }];

export default function Navbar() {
  const [menuOpen, setMenuOpen] = useState(false);
  return <header className="sticky top-0 z-50 border-b border-slate-200 bg-[#FAFAFA]/95 px-4 py-3 backdrop-blur"><div className="mx-auto max-w-7xl overflow-hidden rounded-lg border border-slate-700 bg-slate-900 py-1.5 text-xs font-medium text-slate-100"><div className="telemetry-marquee flex items-center gap-2"><Radio size={13} className="inline text-emerald-400" />LIVE TELEMETRY: Nagpur AWS station reporting 46.2°C · Forecast confidence 96% · 124 nodes online</div></div><nav className="mx-auto mt-3 flex max-w-7xl flex-wrap items-center gap-3 rounded-2xl border-2 border-slate-900 bg-white px-4 py-3 shadow-[3px_3px_0px_0px_#0f172a]" aria-label="Main navigation"><Link to="/" className="flex items-center gap-2 text-lg font-black tracking-tight text-slate-900"><span className="rounded-lg border border-slate-900 bg-amber-100 p-1.5 text-red-700"><Flame size={20} /></span>suryakavach.ai</Link><div className="ml-auto flex items-center gap-2 lg:hidden"><span className="rounded-full bg-emerald-50 px-2 py-1 text-xs font-semibold text-emerald-700">Live</span><button onClick={() => setMenuOpen((open) => !open)} className="rounded-lg border-2 border-slate-900 p-2" aria-label="Toggle menu">{menuOpen ? <X size={18} /> : <Menu size={18} />}</button></div><div className={`${menuOpen ? 'flex' : 'hidden'} w-full flex-col gap-1 border-t border-slate-200 pt-3 text-sm font-medium lg:flex lg:w-auto lg:flex-1 lg:flex-row lg:justify-center lg:border-0 lg:pt-0`}>{links.map((link) => <NavLink key={link.to} onClick={() => setMenuOpen(false)} to={link.to} className={({ isActive }) => `rounded-lg px-3 py-2 transition-colors ${isActive ? 'bg-slate-900 text-white' : 'text-slate-600 hover:bg-slate-100'}`}>{link.label}</NavLink>)}</div><a href="tel:108" className={`${neoButton} hidden items-center gap-2 bg-red-600 text-white lg:flex`}><Phone size={16} />108 Heat Line</a></nav></header>;
}
