import { Activity, Radio, Search, ThermometerSun, Wind } from 'lucide-react';
import { useMemo, useState } from 'react';
import { Bar, BarChart, Cell, Legend, Line, LineChart, Pie, PieChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts';
import { mockCities, mockForecast } from '../data/mockHeatData';
import type { RiskLevel } from '../types/heatwave';
import { getRiskColor, neoCard, neoInput } from '../utils/theme';

const riskDistribution = [{ name: 'Normal', value: 12, color: '#10b981' }, { name: 'Moderate', value: 24, color: '#f59e0b' }, { name: 'Severe', value: 37, color: '#f97316' }, { name: 'Extreme', value: 27, color: '#dc2626' }];
export default function Dashboard() {
  const [query, setQuery] = useState(''); const [risk, setRisk] = useState<'All' | RiskLevel>('All');
  const cities = useMemo(() => mockCities.filter((city) => city.city.toLowerCase().includes(query.toLowerCase()) && (risk === 'All' || city.riskLevel === risk)), [query, risk]);
  return <div className="mx-auto max-w-7xl p-4 md:p-6"><section className="rounded-2xl border border-red-200 border-l-4 border-l-red-600 bg-white p-6 shadow-sm"><div className="flex flex-wrap items-center justify-between gap-5"><div><p className="text-sm font-semibold text-red-700">National heat risk · live</p><h1 className="mt-1 text-3xl font-black text-slate-950">Extreme heat alert</h1><p className="mt-2 text-slate-600">Nagpur AWS-021 is reporting 46.2°C; outdoor work pause conditions are active.</p></div><div className="w-full max-w-md"><div className="h-3 overflow-hidden rounded-full bg-slate-100"><div className="h-full w-[88%] rounded-full bg-gradient-to-r from-emerald-500 via-amber-500 to-red-600" /></div><div className="mt-2 flex justify-between text-xs font-medium text-slate-500"><span>Normal</span><span>Elevated</span><span>Extreme</span></div></div></div></section>
    <section className={`${neoCard} my-5 flex flex-wrap gap-3 bg-white`}><label className="relative flex-1"><Search className="absolute left-3 top-3 text-slate-400" size={18} /><input value={query} onChange={(event) => setQuery(event.target.value)} className={`${neoInput} w-full pl-10`} placeholder="Search city or station" /></label><select value={risk} onChange={(event) => setRisk(event.target.value as 'All' | RiskLevel)} className={neoInput}><option>All severity levels</option><option>Normal</option><option>Moderate</option><option>Severe</option><option>Extreme</option></select></section>
    <section className="grid gap-4 md:grid-cols-2 lg:grid-cols-3">{cities.map((city) => <article key={city.id} className="rounded-2xl border border-slate-200 border-t-4 border-t-slate-700 bg-white p-5 transition-all duration-300 hover:-translate-y-1 hover:border-slate-400 hover:shadow-lg"><div className="flex justify-between gap-2"><div><h2 className="text-lg font-bold">{city.city}</h2><p className="text-sm text-slate-500">{city.state} · {city.awsStationId}</p></div><span className={`h-fit rounded-full border px-2.5 py-1 text-xs font-bold ${getRiskColor(city.riskLevel)}`}>{city.riskLevel}</span></div><div className="mt-4 flex items-end gap-2"><ThermometerSun className="text-red-600" size={26} /><strong className="text-4xl font-black">{city.temp}°C</strong><span className="mb-1 text-sm text-slate-500">Feels {city.feelsLike}°C</span></div><div className="mt-4 grid grid-cols-3 gap-2 text-center text-xs font-medium"><div className="rounded-lg bg-amber-50 p-2 text-amber-800">UV {city.uvIndex}</div><div className="rounded-lg bg-blue-50 p-2 text-blue-800">{city.humidity}% RH</div><div className="rounded-lg bg-slate-100 p-2 text-slate-700">{city.windSpeed} km/h</div></div><p className="mt-3 text-sm text-slate-600">AWS deviance: <b>{city.awsDeviance}</b> · Day {city.heatwaveDaysConsecutive}</p></article>)}</section>
    <section className="mt-6 grid gap-5 lg:grid-cols-2"><article className={`${neoCard} bg-white`}><h2 className="flex items-center gap-2 font-bold"><Activity size={19} />Forecast vs ground truth</h2><p className="mt-1 text-sm text-slate-500">AI maximum, AWS observed ground temperature, and 30-year average.</p><div className="mt-4 h-72"><ResponsiveContainer width="100%" height="100%"><LineChart data={mockForecast}><XAxis dataKey="date" /><YAxis unit="°C" /><Tooltip /><Legend /><Line type="monotone" dataKey="aiPredictedTemp" name="AI Forecast" stroke="#dc2626" strokeWidth={3} /><Line type="monotone" dataKey="awsObservedTemp" name="AWS Ground Truth" stroke="#2563eb" strokeWidth={3} /><Line type="monotone" dataKey="historicalAvg" name="30-Yr Average" stroke="#64748b" strokeWidth={2} /></LineChart></ResponsiveContainer></div></article><article className={`${neoCard} bg-white`}><h2 className="font-bold">National severity risk distribution</h2><p className="mt-1 text-sm text-slate-500">Share of monitored regions by current risk classification.</p><div className="mt-4 h-72"><ResponsiveContainer width="100%" height="100%"><PieChart><Pie data={riskDistribution} dataKey="value" nameKey="name" innerRadius={55} outerRadius={90} paddingAngle={3}>{riskDistribution.map((entry) => <Cell key={entry.name} fill={entry.color} />)}</Pie><Tooltip /><Legend /></PieChart></ResponsiveContainer></div></article></section>
    <section className={`${neoCard} mt-6 bg-white`}><h2 className="font-bold">Peak maximum temperature comparison by city</h2><div className="mt-4 h-72"><ResponsiveContainer width="100%" height="100%"><BarChart data={mockCities}><XAxis dataKey="city" tick={{ fontSize: 12 }} /><YAxis unit="°C" /><Tooltip /><Bar dataKey="temp" name="Current maximum" fill="#dc2626" radius={[6, 6, 0, 0]} /></BarChart></ResponsiveContainer></div></section>
    <section className="mt-6 rounded-2xl border border-emerald-200 bg-emerald-50 p-6"><h2 className="flex items-center gap-2 font-bold text-emerald-900"><Radio size={18} />AWS station telemetry</h2><div className="mt-3 grid gap-3 md:grid-cols-3">{mockCities.slice(0, 3).map((city) => <div key={city.id} className="rounded-xl border border-emerald-200 bg-white p-4"><b>{city.awsStationId}</b><p className="mt-1 text-sm text-slate-600">Packet received 12 seconds ago</p><p className="mt-2 text-sm">{city.city}: {city.temp}°C · <Wind className="inline" size={14} /> {city.windSpeed} km/h</p></div>)}</div></section></div>;
}
