import { Activity, BrainCircuit, ChevronRight, HeartHandshake, MapPinned, Radio, ShieldAlert, SunMedium, UsersRound } from 'lucide-react';
import { useState } from 'react';
import { Link } from 'react-router-dom';
import { mockCities } from '../data/mockHeatData';
import { getRiskColor, neoButton, neoCard } from '../utils/theme';

const pipeline = [
  { title: 'Data Acquisition', detail: 'IMD climate history and real-time IoT AWS observations create a localized source of truth.', metric: '124 active nodes' },
  { title: 'Data Analytics', detail: 'Spatio-temporal analysis detects emerging heat patterns across neighbourhoods and regions.', metric: '7 climate zones' },
  { title: 'AI Intelligence', detail: 'Forecast models classify risk, estimate maximum temperature, and identify heat hotspots.', metric: '94.8% accuracy' },
  { title: 'Forecast Validation', detail: 'AI forecasts are continuously compared with AWS ground-truth readings.', metric: '±0.4°C deviation' },
  { title: 'LLM Advisory Engine', detail: 'Complex climate evidence becomes clear, persona-specific actions for people and agencies.', metric: '4 advisory portals' },
];
const features = [
  { icon: MapPinned, title: 'Hotspot mapping', text: 'See where heat pressure is concentrating before the afternoon peak.', tint: 'bg-blue-50 text-blue-700' },
  { icon: BrainCircuit, title: 'AI advisories', text: 'Turn live risk into practical guidance for citizens and care teams.', tint: 'bg-violet-50 text-violet-700' },
  { icon: Radio, title: 'AWS validation', text: 'Keep forecasts accountable with near-real-time ground telemetry.', tint: 'bg-emerald-50 text-emerald-700' },
  { icon: ShieldAlert, title: 'Emergency routing', text: 'Connect people with cooling centers and urgent support faster.', tint: 'bg-red-50 text-red-700' },
];

export default function Landing() {
  const [activeLayer, setActiveLayer] = useState(0);
  const currentLayer = pipeline[activeLayer];
  return <div className="relative mx-auto max-w-7xl p-4 md:p-6">
    <div className="pointer-events-none absolute left-1/2 top-0 z-0 h-full w-screen -translate-x-1/2" style={{ backgroundImage: 'repeating-linear-gradient(22.5deg, transparent, transparent 2px, rgba(75, 85, 99, 0.06) 2px, rgba(75, 85, 99, 0.06) 3px, transparent 3px, transparent 8px), repeating-linear-gradient(67.5deg, transparent, transparent 2px, rgba(107, 114, 128, 0.05) 2px, rgba(107, 114, 128, 0.05) 3px, transparent 3px, transparent 8px), repeating-linear-gradient(112.5deg, transparent, transparent 2px, rgba(55, 65, 81, 0.04) 2px, rgba(55, 65, 81, 0.04) 3px, transparent 3px, transparent 8px), repeating-linear-gradient(157.5deg, transparent, transparent 2px, rgba(31, 41, 55, 0.03) 2px, rgba(31, 41, 55, 0.03) 3px, transparent 3px, transparent 8px)' }} />
    <div className="relative z-10">
      <section className="grid gap-8 rounded-3xl border-2 border-slate-900 bg-white/90 p-7 shadow-[4px_4px_0px_0px_#0f172a] md:grid-cols-[1.05fr_.95fr] md:p-12">
        <div><span className="inline-flex items-center gap-2 rounded-full border-2 border-slate-900 bg-red-50 px-3 py-1.5 text-sm font-semibold text-red-700"><span className="relative flex h-2.5 w-2.5"><span className="absolute inline-flex h-full w-full animate-ping rounded-full bg-red-500 opacity-75" /><span className="relative inline-flex h-2.5 w-2.5 rounded-full bg-red-600" /></span>Live telemetry active</span><h1 className="mt-6 text-4xl font-black tracking-tight text-slate-950 md:text-6xl">Predict extreme heat.<br />Protect vulnerable cities.</h1><p className="mt-5 max-w-xl text-lg leading-8 text-slate-600">suryakavach.ai brings IMD climate data, IoT ground truth, AI forecasting, and human-ready safety advice together for the people who need it most.</p><div className="mt-7 flex flex-wrap gap-3"><Link to="/dashboard" className={`${neoButton} bg-blue-600 text-white`}>Explore live heat map <ChevronRight className="ml-1 inline" size={17} /></Link><Link to="/advisory" className={`${neoButton} bg-white text-slate-800`}>View AI advisories</Link></div><div className="mt-8 flex items-center gap-3"><div className="flex -space-x-2"><span className="grid h-9 w-9 place-items-center rounded-full border-2 border-white bg-amber-200 text-xs font-bold">AS</span><span className="grid h-9 w-9 place-items-center rounded-full border-2 border-white bg-rose-200 text-xs font-bold">RK</span><span className="grid h-9 w-9 place-items-center rounded-full border-2 border-white bg-sky-200 text-xs font-bold">NM</span></div><p className="text-sm text-slate-600"><b className="text-slate-900">Built with local responders.</b><br />Designed for safer heat decisions.</p></div></div>
        <div className="rounded-2xl border-2 border-slate-900 bg-slate-950 p-4 shadow-[4px_4px_0px_0px_#0f172a]"><div className="flex items-center justify-between text-xs font-medium text-slate-300"><span className="flex items-center gap-2"><Activity size={14} className="text-emerald-400" />National heat map</span><span>Updated 12 sec ago</span></div><div className="relative mt-4 h-56 overflow-hidden rounded-xl border border-slate-700 bg-[radial-gradient(circle_at_23%_38%,#ef4444_0,transparent_14%),radial-gradient(circle_at_65%_33%,#f97316_0,transparent_17%),radial-gradient(circle_at_54%_70%,#f59e0b_0,transparent_15%),linear-gradient(135deg,#172554,#0f172a)]"><span className="absolute left-[20%] top-[32%] h-5 w-5 animate-pulse rounded-full border-2 border-white bg-red-500 shadow-[0_0_20px_8px_#ef444488]" /><span className="absolute left-[62%] top-[28%] h-4 w-4 animate-pulse rounded-full border-2 border-white bg-orange-400 shadow-[0_0_20px_8px_#f9731688]" /><span className="absolute left-[49%] top-[68%] h-4 w-4 animate-pulse rounded-full border-2 border-white bg-amber-300 shadow-[0_0_20px_8px_#f59e0b88]" /><div className="absolute bottom-3 left-3 rounded-lg bg-slate-900/80 px-3 py-2 text-xs text-white"><b>Nagpur AWS-021</b><br />46.2°C · Extreme</div></div><div className="mt-3 grid grid-cols-3 gap-2 text-center text-xs"><div className="rounded-lg bg-slate-800 p-2 text-slate-200"><b className="block text-emerald-400">124</b>AWS nodes</div><div className="rounded-lg bg-slate-800 p-2 text-slate-200"><b className="block text-orange-400">06</b>active alerts</div><div className="rounded-lg bg-slate-800 p-2 text-slate-200"><b className="block text-blue-400">96%</b>confidence</div></div></div>
      </section>
      <section className="my-8 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{[['124+', 'AWS Nodes Active', Radio], ['94.8%', 'AI Prediction Accuracy', BrainCircuit], ['7', 'Climate Zones Tracked', SunMedium], ['4.2M', 'Citizens Covered', UsersRound]].map(([value, label, Icon]) => { const StatIcon = Icon as typeof Radio; return <article key={label as string} className="rounded-2xl border-2 border-slate-900 bg-white/90 p-5 shadow-[3px_3px_0px_0px_#0f172a] transition-all duration-300 hover:-translate-y-1 hover:shadow-lg"><StatIcon className="text-blue-600" size={20} /><p className="mt-3 text-3xl font-black text-slate-900">{value as string}</p><p className="mt-1 text-sm font-medium text-slate-600">{label as string}</p></article>; })}</section>
      <section className={`${neoCard} mb-8 bg-white/95`}><div className="flex flex-wrap items-end justify-between gap-3"><div><p className="text-sm font-semibold text-blue-700">How the system works</p><h2 className="mt-1 text-2xl font-black">Five layers, one reliable heat signal</h2></div><span className="rounded-full border border-slate-200 bg-slate-50 px-3 py-1 text-sm font-medium text-slate-600">Interactive pipeline</span></div><div className="mt-6 flex flex-wrap gap-2">{pipeline.map((layer, index) => <button key={layer.title} onClick={() => setActiveLayer(index)} className={`rounded-xl border-2 px-3 py-2 text-sm font-semibold transition-all ${activeLayer === index ? 'border-slate-900 bg-blue-600 text-white shadow-[2px_2px_0px_0px_#0f172a]' : 'border-slate-900 bg-white text-slate-600 hover:-translate-y-0.5 hover:shadow-[2px_2px_0px_0px_#0f172a]'}`}>{index + 1}. {layer.title}</button>)}</div><div className="mt-5 rounded-2xl border-2 border-slate-900 bg-slate-50 p-5"><p className="text-sm font-semibold text-blue-700">Layer {activeLayer + 1}</p><h3 className="mt-1 text-xl font-bold">{currentLayer.title}</h3><p className="mt-2 max-w-3xl text-slate-600">{currentLayer.detail}</p><span className="mt-4 inline-block rounded-lg border border-slate-300 bg-white px-3 py-1.5 text-sm font-semibold text-slate-700">{currentLayer.metric}</span></div></section>
      <section className="mb-8"><div className="mb-4 flex items-end justify-between"><div><p className="text-sm font-semibold text-red-700">Live regional risk</p><h2 className="text-2xl font-black">Cities needing attention now</h2></div><Link to="/dashboard" className="text-sm font-semibold text-blue-700">View all telemetry →</Link></div><div className="grid gap-4 md:grid-cols-3">{mockCities.slice(0, 3).map((city) => <article key={city.id} className="rounded-2xl border-2 border-slate-900 bg-white/95 p-5 shadow-[3px_3px_0px_0px_#0f172a] transition-all duration-300 hover:-translate-y-1 hover:shadow-lg"><div className="flex items-start justify-between"><div><h3 className="font-bold">{city.city}</h3><p className="text-sm text-slate-500">{city.awsStationId}</p></div><span className={`rounded-full border px-2.5 py-1 text-xs font-bold ${getRiskColor(city.riskLevel)}`}>{city.riskLevel}</span></div><p className="mt-5 text-3xl font-black">{city.temp}°C</p><div className="mt-4 flex justify-between text-sm text-slate-600"><span>Wind {city.windSpeed} km/h</span><span>UV {city.uvIndex}</span></div></article>)}</div></section>
      <section className="grid gap-4 md:grid-cols-4">{features.map(({ icon: Icon, title, text, tint }) => <article key={title} className="rounded-2xl border-2 border-slate-900 bg-white/95 p-6 shadow-[3px_3px_0px_0px_#0f172a] transition-all duration-300 hover:-translate-y-1 hover:shadow-xl"><span className={`grid h-11 w-11 place-items-center rounded-xl ${tint}`}><Icon size={23} /></span><h3 className="mt-4 text-lg font-bold">{title}</h3><p className="mt-2 text-sm leading-6 text-slate-600">{text}</p></article>)}</section>
      <section className="my-8 flex flex-wrap items-center justify-between gap-5 rounded-3xl border-2 border-slate-900 bg-slate-900 p-8 text-white shadow-[4px_4px_0px_0px_#0f172a] md:p-10"><div className="flex items-start gap-4"><HeartHandshake className="mt-1 text-amber-300" size={28} /><div><p className="text-sm font-semibold text-blue-300">Decision support, when it matters</p><h2 className="mt-1 text-3xl font-black">Make the next heat decision with confidence.</h2><p className="mt-2 max-w-xl text-slate-300">Explore verified forecasts, risk indicators, and local response options in one workspace.</p></div></div><Link to="/dashboard" className={`${neoButton} bg-white text-slate-900`}>Open decision dashboard</Link></section>
    </div>
  </div>;
}
